# Generated by Django 5.2.2 on 2025-07-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='servico',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servicos',
            field=models.ManyToManyField(to='agendamento.servico'),
        ),
    ]
